- name: Create wooh.hu default A
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: 46.101.115.175
    type: A
    name: "@"
    force_update: yes

- name: Create google MX records
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    priority: "{{ item.priority }}"
    data: "{{ item.data }}"
    type: MX
  loop:
    - {priority: 10, data: "aspmx.l.google.com"}
    - {priority: 20, data: "alt1.aspmx.l.google.com"}
    - {priority: 20, data: "alt2.aspmx.l.google.com"}
    - {priority: 30, data: "aspmx2.googlemail.com"}
    - {priority: 30, data: "aspmx3.googlemail.com"}
    - {priority: 30, data: "aspmx4.googlemail.com"}
    - {priority: 30, data: "aspmx5.googlemail.com"}

- name: Create vpn.wooh.hu
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    name: vpn
    type: A
    data: "{{ vpn_ip }}"

- name: Create CNAME records
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    name: "{{ item }}"
    data: wooh.hu
    type: CNAME
  loop:
    - eni
    - munkacsy
    - otaku
    - pomodoro
    - wedding
    - www

- name: Create url.wooh.hu
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    name: url
    data: ghs.googlehosted.com
    type: CNAME

- name: Create blog.wooh.hu hosted on github
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    name: blog
    data: woohgit.github.io
    type: CNAME

- name: Create spf TXT record
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: "v=spf1 include:_spf.google.com ~all"
    type: TXT

- name: Create A record for fra1-01
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: 46.101.115.175
    name: fra1-01
    type: A
