- name: wooh.hu default A
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: 46.101.115.175
    type: A
    name: "@"

- name: Google MX records
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    priority: "{{ item.priority }}"
    data: "{{ item.data }}"
    type: MX
  loop:
    - {priority: 10, data: "aspmx.l.google.com"}
    - {priority: 20, data: "alt1.aspmx.l.google.com"}
    - {priority: 20, data: "alt2.aspmx.l.google.com"}
    - {priority: 30, data: "aspmx2.googlemail.com"}
    - {priority: 30, data: "aspmx3.googlemail.com"}
    - {priority: 30, data: "aspmx4.googlemail.com"}
    - {priority: 30, data: "aspmx5.googlemail.com"}

- name: CNAME records
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    name: "{{ item }}"
    data: wooh.hu
    type: CNAME
  loop:
    - pomodoro
    - www

- name: url.wooh.hu
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    name: url
    data: ghs.googlehosted.com
    type: CNAME

- name: blog.wooh.hu hosted on github
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    name: blog
    data: woohgit.github.io
    type: CNAME

- name: SPF verification record
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: "v=spf1 include:_spf.google.com ~all"
    type: TXT

- name: Keybase verification TXT record
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: "keybase-site-verification=CbPU5ogtUu2wewVzdwYpB6Ol12f9gFsfAqog6zZ7HYM"
    type: TXT

- name: Create A record for fra1-01
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: 46.101.115.175
    name: fra1-01
    type: A
