- name: Create hangbolt.com domain
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: 146.185.183.251
    type: A
    create_domain: yes

- name: Create MX records
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    priority: "{{ item.priority }}"
    data: "{{ item.data }}"
    type: MX
  loop:
    - {priority: 10, data: "aspmx.l.google.com"}
    - {priority: 20, data: "alt1.aspmx.l.google.com"}
    - {priority: 20, data: "alt2.aspmx.l.google.com"}
    - {priority: 30, data: "aspmx2.googlemail.com"}
    - {priority: 30, data: "aspmx3.googlemail.com"}
    - {priority: 30, data: "aspmx4.googlemail.com"}
    - {priority: 30, data: "aspmx5.googlemail.com"}

- name: Create google site verification TXT record
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: "google-site-verification=isv9th9Fm5LB6JYElRRFfMe1FTqa8oSeBhKb-k2l73c"
    type: TXT

- name: Create spf TXT record
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: "v=spf1 mx ip4:146.185.183.251 a:otaku.wooh.hu ?all"
    type: TXT

- name: Create aliases
  digital_ocean_domain_record:
    oauth_token: "{{ oauth_token }}"
    domain: "{{ domain }}"
    data: wooh.hu
    name: "{{ item }}"
    type: CNAME
  loop:
    - shop
    - test
    - www

